version: '3.8'
services:
  js_dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.js_dev
    volumes:
        - ./src/frontend:/workdir
    networks:
      - dev_net
  go_dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.go_dev
    volumes:
      - ./src/backend:/workdir
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev_net
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev_root_1209
    networks:
      - dev_net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: DevRoot@1209
      ME_CONFIG_MONGODB_URL: mongodb://root:dev_root_1209@mongodb:27017/
    networks:
      - dev_net
networks:
  dev_net:
